apiVersion: v1
kind: Service
metadata:
  name: sticky-backend
  labels:
    app: sticky-backend
spec:
  ports:
  - port: 80
  clusterIP: None
  selector:
    app: sticky-backend
    tier: backend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sticky-backend
spec:
  serviceName: sticky-backend
  replicas: 3
  selector:
    matchLabels:
      app: sticky-backend
      tier: backend
  template:
    metadata:
      labels:
        app: sticky-backend
        tier: backend
    spec:
      containers:
      - name: sticky-backend
        image: damdo/mirror
        env:
          - name: BODY
            value: "0"
        ports:
        - containerPort: 80
          name: web
